name: si-actions
run-name: Ciao da ${{ github.actor }} 
on: [push]
jobs:
  si-fa-cose:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fineeeeeeeeeeeeeeeeeeeeeeeeeeee"
      - run: java -version
      - run: ls -la
      - run: uname -a
      - run: whoami
      - run: uptime
      - run: env
      - run: pwd
      - run: date
      - run: lsb_release -a
